import { MAT, SKILLS, type SkillCounts } from '../core/types';
import type { LevelDef } from './types';

function sk(partial: Partial<SkillCounts>): SkillCounts {
  const out = {} as SkillCounts;
  for (const s of SKILLS) out[s] = partial[s] ?? 0;
  return out;
}

/**
 * Welt 4 — die Frostklamm.
 *
 * „Hohe, schmale Level. Der Weg fuehrt nach unten, und unten wartet der
 * Aufprall." (`welten.ts`). Vierzehn Level, drei Kapitel: **Kante** lernt das
 * Hinabkommen, **Absturz** verlangt es unter Druck, **Tiefe** prueft.
 *
 * ## Die Entwurfsregeln dieser Welt
 *
 * 1. **Die Fallhoehe ist der Gegner.** Fast jedes Raetsel fragt: Wie kommen
 *    alle heil nach unten? Absaetze von siebzig Bildpunkten sind die
 *    Waehrung; was darueber liegt, braucht Schirm, Schacht oder Bruecke.
 * 2. **Schmal statt breit.** 480 Bildpunkte Breite, bis zu 860 Hoehe — die
 *    Klamm ist ein Schacht, kein Land. Die Weltwaende sind Spielflaeche.
 * 3. **Blankeis ist der Stahl dieser Welt.** Dieselbe Simulation, andere
 *    Erzaehlung: Was glaenzt, traegt kein Werkzeug.
 * 4. **Der Pulk startet eingezaeunt.** Wo die Route mit einem Absturz
 *    beginnt, haelt ein Pfercht die Unbeaufsichtigten — Sackgassen fangen
 *    mit Warten, nie mit Sterben (Falltuer-Probe im Testlauf).
 */
export const WELT4_LEVELS: LevelDef[] = [
  {
    id: 'w4-01',
    name: 'Die Kante',
    chapter: 'Kante',
    hint: 'Die Klamm trägt dich — noch. Absatz für Absatz, keiner tiefer als ein Körper fällt.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41001,
    entrance: { x: 240, y: 140 },
    exit: { x: 224, y: 460, w: 32, h: 26 },
    total: 10,
    needed: 8,
    timeLimitSec: 120,
    releaseRate: 50,
    minReleaseRate: 30,
    skills: sk({ digger: 2 }),
    par: 0,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      // Die Kaskade: Absaetze im Wechsel, jeder siebzig tief.
      { t: 'rect', x: 0, y: 200, w: 380, h: 12, mat: MAT.ROCK },
      { t: 'rect', x: 100, y: 270, w: 380, h: 12, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 340, w: 380, h: 12, mat: MAT.ROCK },
      { t: 'rect', x: 100, y: 410, w: 380, h: 12, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 480, h: 140, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-02',
    name: 'Schirmpflicht',
    chapter: 'Kante',
    hint: 'Unter dem Pfercht wartet die halbe Klamm. Grabe auf — und schirme jeden, der fällt.',
    theme: 'frost',
    width: 480,
    height: 800,
    seed: 41002,
    entrance: { x: 240, y: 140 },
    exit: { x: 380, y: 700, w: 32, h: 26 },
    total: 12,
    needed: 6,
    timeLimitSec: 150,
    releaseRate: 30,
    minReleaseRate: 20,
    skills: sk({ floater: 8, digger: 2 }),
    par: 7,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      // Der Pfercht: ein Sims mit Waenden, sicher fuer alle, die warten.
      { t: 'rect', x: 120, y: 200, w: 240, h: 70, mat: MAT.ROCK },
      { t: 'rect', x: 120, y: 140, w: 10, h: 60, mat: MAT.ROCK },
      { t: 'rect', x: 350, y: 140, w: 10, h: 60, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 720, h: 80, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-03',
    name: 'Zwei Kanten',
    chapter: 'Kante',
    hint: 'Die Kante lügt, der Schacht trägt: zweimal senkrecht, und jeder Absatz bleibt unter der Grenze.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41003,
    entrance: { x: 180, y: 170 },
    exit: { x: 240, y: 350, w: 32, h: 26 },
    total: 14,
    needed: 10,
    timeLimitSec: 180,
    releaseRate: 45,
    minReleaseRate: 25,
    skills: sk({ digger: 4, blocker: 2 }),
    par: 2,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      // Oberes Sims mit Pferchtwand rechts; links haelt die Weltwand.
      { t: 'rect', x: 0, y: 230, w: 360, h: 58, mat: MAT.ROCK },
      { t: 'rect', x: 348, y: 170, w: 12, h: 60, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 300, w: 480, h: 58, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 370, h: 250, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-04',
    name: 'Eisbrücke',
    chapter: 'Kante',
    hint: 'Zwei Türme, dazwischen nichts. Die Brücke braucht Nachschub, bevor die letzte Stufe liegt.',
    theme: 'frost',
    width: 480,
    height: 720,
    seed: 41004,
    entrance: { x: 110, y: 240 },
    exit: { x: 400, y: 280, w: 32, h: 26 },
    total: 14,
    needed: 10,
    timeLimitSec: 160,
    releaseRate: 45,
    minReleaseRate: 25,
    skills: sk({ builder: 4, floater: 2, blocker: 2 }),
    par: 2,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 300, w: 220, h: 420, mat: MAT.ROCK },
      { t: 'rect', x: 252, y: 300, w: 228, h: 420, mat: MAT.ROCK },
      // Der Spaltgrund faengt, wer vor der Bruecke faellt — ohne Rueckweg.
      { t: 'rect', x: 220, y: 360, w: 32, h: 360, mat: MAT.ROCK },
    ],
  },
  {
    id: 'w4-05',
    name: 'Wächter der Kante',
    chapter: 'Absturz',
    hint: 'Die zweite Etage hat eine offene Westkante. Erst der Wächter, dann der zweite Schacht.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41005,
    entrance: { x: 240, y: 160 },
    exit: { x: 400, y: 270, w: 32, h: 26 },
    total: 16,
    needed: 10,
    timeLimitSec: 200,
    releaseRate: 55,
    minReleaseRate: 30,
    skills: sk({ digger: 4, blocker: 3, floater: 2 }),
    par: 3,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 220, w: 480, h: 58, mat: MAT.ROCK },
      // Die Terrasse endet im Westen ueber dem Abgrund — dort steht der
      // Waechter, oder es stirbt der Pulk. Unter der Kante liegt nur das
      // ferne Becken.
      { t: 'rect', x: 120, y: 290, w: 360, h: 330, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 120, y: 520, h: 100, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-06',
    name: 'Doppelsprung',
    chapter: 'Absturz',
    hint: 'Zwei Stürze, ein Schirm: Wer einmal schweben kann, kann es auch beim zweiten Mal.',
    theme: 'frost',
    width: 480,
    height: 860,
    seed: 41006,
    entrance: { x: 240, y: 140 },
    exit: { x: 224, y: 770, w: 32, h: 26 },
    total: 12,
    needed: 6,
    timeLimitSec: 180,
    releaseRate: 30,
    minReleaseRate: 20,
    skills: sk({ floater: 8, digger: 2 }),
    par: 7,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 120, y: 200, w: 240, h: 70, mat: MAT.ROCK },
      { t: 'rect', x: 120, y: 140, w: 10, h: 60, mat: MAT.ROCK },
      { t: 'rect', x: 350, y: 140, w: 10, h: 60, mat: MAT.ROCK },
      // Der Zwischenhalt — und von seinen Kanten geht es gleich weiter.
      { t: 'rect', x: 120, y: 520, w: 260, h: 16, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 790, h: 70, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-07',
    name: 'Gegenwind',
    chapter: 'Absturz',
    hint: 'Ganz unten steht ein Pfeiler, und auf dem Pfeiler die Tür. Hinauf hilft nur der Kletterer.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41007,
    entrance: { x: 240, y: 160 },
    exit: { x: 72, y: 336, w: 32, h: 26 },
    total: 12,
    needed: 6,
    timeLimitSec: 180,
    releaseRate: 40,
    minReleaseRate: 25,
    skills: sk({ climber: 8, floater: 2, builder: 2 }),
    par: 6,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 220, w: 380, h: 12, mat: MAT.ROCK },
      { t: 'rect', x: 100, y: 290, w: 380, h: 12, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 430, h: 190, mat: MAT.ROCK, rough: 2 },
      // Der Pfeiler mit der Tuer — siebzig hoch, nur fuer Kletterer.
      { t: 'rect', x: 60, y: 360, w: 60, h: 70, mat: MAT.ROCK },
    ],
  },
  {
    id: 'w4-08',
    name: 'Eisnaht',
    chapter: 'Absturz',
    hint: 'Blankeis trägt kein Werkzeug — aber die Naht trägt eine Sprengung. Hundert Bildpunkte Vorhalt.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41008,
    entrance: { x: 240, y: 340 },
    exit: { x: 400, y: 440, w: 32, h: 26 },
    total: 14,
    needed: 10,
    timeLimitSec: 150,
    releaseRate: 45,
    minReleaseRate: 25,
    skills: sk({ bomber: 3, digger: 2 }),
    par: 1,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      // Firnschicht auf Blankeis, mit einer Naht bei 180.
      { t: 'rect', x: 0, y: 396, w: 480, h: 2, mat: MAT.EARTH },
      { t: 'rect', x: 0, y: 398, w: 480, h: 3, mat: MAT.STEEL },
      { t: 'rect', x: 180, y: 398, w: 4, h: 3, mat: MAT.EARTH },
      { t: 'ground', x: 0, w: 480, y: 460, h: 160, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-09',
    name: 'Schrägfahrt',
    chapter: 'Absturz',
    hint: 'Zwei Schrägen im Zickzack durch den Berg — die zweite beginnt am Boden der ersten Kammer.',
    theme: 'frost',
    width: 480,
    height: 720,
    seed: 41009,
    entrance: { x: 380, y: 140 },
    exit: { x: 360, y: 454, w: 32, h: 26 },
    total: 12,
    needed: 8,
    timeLimitSec: 220,
    releaseRate: 40,
    minReleaseRate: 25,
    skills: sk({ miner: 4, blocker: 2 }),
    par: 2,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 200, w: 480, h: 520, mat: MAT.ROCK },
      { t: 'rect', x: 40, y: 280, w: 160, h: 60, mat: MAT.EMPTY },
      { t: 'rect', x: 240, y: 420, w: 180, h: 60, mat: MAT.EMPTY },
    ],
  },
  {
    id: 'w4-10',
    name: 'Vier Kanten',
    chapter: 'Tiefe',
    hint: 'Die mittlere Etage hängt frei: zwei offene Kanten, zwei Wächter — und erst dann der Schacht.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41010,
    entrance: { x: 240, y: 160 },
    exit: { x: 224, y: 270, w: 32, h: 26 },
    total: 16,
    needed: 9,
    timeLimitSec: 220,
    releaseRate: 55,
    minReleaseRate: 30,
    skills: sk({ digger: 4, blocker: 3 }),
    par: 4,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 220, w: 480, h: 58, mat: MAT.ROCK },
      // Die freie Terrasse: beide Kanten offen, unter beiden der lange Fall.
      { t: 'rect', x: 120, y: 290, w: 240, h: 330, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 120, y: 520, h: 100, mat: MAT.ROCK, rough: 2 },
      { t: 'ground', x: 360, w: 120, y: 520, h: 100, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-11',
    name: 'Über die Klamm',
    chapter: 'Tiefe',
    hint: 'Vierundvierzig Bildpunkte Leere, kein Grund in Sicht. Drei Bauer in einer Kette tragen hinüber.',
    theme: 'frost',
    width: 480,
    height: 800,
    seed: 41011,
    entrance: { x: 70, y: 180 },
    exit: { x: 400, y: 220, w: 32, h: 26 },
    total: 16,
    needed: 10,
    timeLimitSec: 220,
    releaseRate: 40,
    minReleaseRate: 25,
    skills: sk({ builder: 4, floater: 2, blocker: 2 }),
    par: 3,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 240, w: 140, h: 560, mat: MAT.ROCK },
      { t: 'rect', x: 184, y: 240, w: 296, h: 560, mat: MAT.ROCK },
      { t: 'rect', x: 140, y: 300, w: 44, h: 500, mat: MAT.ROCK },
    ],
  },
  {
    id: 'w4-12',
    name: 'Eile im Eis',
    chapter: 'Tiefe',
    hint: 'Dieselben zwei Schächte wie am Anfang — nur die Uhr ist eine andere.',
    theme: 'frost',
    width: 480,
    height: 620,
    seed: 41012,
    entrance: { x: 180, y: 170 },
    exit: { x: 240, y: 350, w: 32, h: 26 },
    total: 14,
    needed: 11,
    timeLimitSec: 70,
    releaseRate: 60,
    minReleaseRate: 40,
    skills: sk({ digger: 4, blocker: 1 }),
    par: 2,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 230, w: 360, h: 58, mat: MAT.ROCK },
      { t: 'rect', x: 348, y: 170, w: 12, h: 60, mat: MAT.ROCK },
      { t: 'rect', x: 0, y: 300, w: 480, h: 58, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 370, h: 250, mat: MAT.ROCK, rough: 2 },
    ],
  },
  {
    id: 'w4-13',
    name: 'Zurück ans Licht',
    chapter: 'Tiefe',
    hint: 'Drei Stufen, jede zu hoch zum Steigen. Die Klamm lässt nur Kletterer wieder hinauf.',
    theme: 'frost',
    width: 480,
    height: 720,
    seed: 41013,
    entrance: { x: 80, y: 550 },
    exit: { x: 420, y: 390, w: 32, h: 26 },
    total: 12,
    needed: 6,
    timeLimitSec: 180,
    releaseRate: 40,
    minReleaseRate: 25,
    skills: sk({ climber: 8, floater: 2, builder: 2 }),
    par: 6,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      { t: 'ground', x: 0, w: 480, y: 620, h: 100, mat: MAT.ROCK, rough: 2 },
      // Die Treppe aus dem Schacht: drei Bloecke, jeder siebzig hoch.
      { t: 'rect', x: 160, y: 550, w: 320, h: 70, mat: MAT.ROCK },
      { t: 'rect', x: 260, y: 480, w: 220, h: 70, mat: MAT.ROCK },
      { t: 'rect', x: 360, y: 410, w: 120, h: 70, mat: MAT.ROCK },
    ],
  },
  {
    id: 'w4-14',
    name: 'Prüfung in der Klamm',
    chapter: 'Tiefe',
    hint: 'Schacht, Wächter, Naht, Riegel — die ganze Klamm in einem Abstieg.',
    theme: 'frost',
    width: 480,
    height: 860,
    seed: 41014,
    entrance: { x: 240, y: 140 },
    exit: { x: 368, y: 384, w: 32, h: 26 },
    total: 16,
    needed: 8,
    timeLimitSec: 260,
    releaseRate: 50,
    minReleaseRate: 25,
    skills: sk({ digger: 3, blocker: 2, bomber: 2, basher: 2, floater: 2, climber: 2 }),
    par: 5,
    paint: [
      { t: 'rect', x: 0, y: 60, w: 480, h: 20, mat: MAT.ROCK },
      // Der Pfercht ganz oben, 58 duenn.
      { t: 'rect', x: 0, y: 200, w: 480, h: 58, mat: MAT.ROCK },
      // Die Mitteletage mit offener Westkante — unter ihr, links der Platte,
      // geht es bis zum Grund durch (140 tief: toedlich).
      { t: 'rect', x: 120, y: 270, w: 360, h: 58, mat: MAT.ROCK },
      // Firn auf Blankeis, die Naht bei 200 — im Westen, denn jeder, der
      // vom Schacht kommt, laeuft westwaerts; die Platte beginnt erst bei 140.
      { t: 'rect', x: 140, y: 340, w: 340, h: 2, mat: MAT.EARTH },
      { t: 'rect', x: 140, y: 342, w: 340, h: 3, mat: MAT.STEEL },
      { t: 'rect', x: 200, y: 342, w: 4, h: 3, mat: MAT.EARTH },
      // Der Grund, glatt: hier arbeitet der Rammer. Der Riegel traegt die Tuer.
      { t: 'ground', x: 0, w: 480, y: 410, h: 450, mat: MAT.ROCK, rough: 0 },
      { t: 'rect', x: 360, y: 345, w: 40, h: 65, mat: MAT.ROCK },
    ],
  },
];
